FROM openjdk:8-jdk-alpine
EXPOSE 8080
COPY build/libs/tema-7-microservices-0.0.1-SNAPSHOT.jar tema-7-microservices-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/tema-7-microservices-0.0.1-SNAPSHOT.jar"]